site_name: Documentation
nav:
  - Общая информация:
    - gi/index.md
    - Описание инструмента: gi/tool description.md
    - gi/user workstation requirements.md
  - Руководство пользователя:
    - ug/index.md
    - ug/work with applications.md
    - Installation: getting-started.md
    - Creating your site: creating-your-site.md
    - Publishing your site: publishing-your-site.md
    - Customization: customization.md
    - Browser support: browser-support.md
    - Alternatives: alternatives.md
    - License: license.md
    - Changelog:
      - changelog/index.md
      - How to upgrade: upgrade.md
  
theme:
  language: ru
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: appsechub
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
extra_css:
  - stylesheets/extra.css

plugins:
  - git-revision-date-localized:
      type: iso_datetime
  - search:
      lang: 
        - en
        - ru

repo_url: https://github.com/andreygladilin/mktest
repo_name: andreygladilin/mktest

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/github 
      link: https://twitter.com/squidfunk


